### ISSUE TITLE
Windows + Python 3.8 Builds failing

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/zaber-motion-feedstock#2]
Needs: https://github.com/conda-forge/pywin32-feedstock/pull/21

**Comment by carlodri** [comment]
please check if pywin32 v227 solves the issue.

**Comment by hmaarrfk** [comment]
Thanks for looking into this.

Seems like i'm still having the issue.

I seem to have hammered their servers too hard, so i'm going to refrain from building until you have time to look at this agian.

**Comment by hmaarrfk** [comment]
it ended up being about some enhanced security in python 3.8.

I used `find_library` before calling `load_library`

**Comment by carlodri** [comment]
just to clarify: so this is not related to pywin32?

**Comment by hmaarrfk** [comment]
Not related to pywin32
